name: Laravel CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      # Lấy source code
      - uses: actions/checkout@v3

      # Cài PHP version 8.1
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, intl, bcmath, pdo_mysql
          coverage: none

      # Cài dependency Laravel
      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      # Copy env file
      - name: Copy env
        run: cp .env.example .env

      # Ghi đè DB config cho CI
      - name: Setup env for CI
        run: |
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=laravel" >> .env
          echo "DB_USERNAME=root" >> .env
          echo "DB_PASSWORD=root" >> .env

      # Tạo app key
      - name: Generate app key
        run: php artisan key:generate

      # Run migrate
      - name: Run migrations
        run: php artisan migrate --force

      # Run PHPUnit / Pest test
      - name: Run tests
        run: php artisan test
